### ISSUE TITLE
State file for the watch mode

### ISSUE THREAD

**Issue by Zerotask** [rust-lang/rustlings#729]
Based on the idea by @panpansuannai #727 and as mentioned here https://github.com/rust-lang/rustlings/pull/727#issuecomment-826066962
rustlings could remember the last successful exercise or the next / current exercise in a simple text file.

This would offer the possibility to skip the long-taking checks by `rustlings watch` if you pass an additional flag, e. g. `-c`, `--continue`

Edit:
> Use Case:
You start with Rustlings and every day you complete some exercises. Therefore you just want to continue where you stopped.

**Comment by VuiMuich** [comment]
as an alternative or as an addition rustlings could skip tests for exercises that have removed the `// I AM NOT DONE` lines

**Comment by Zerotask** [comment]
But rustlings have to either read every file to check that or have to run a local DB (SQLite for example) to remember which files have this line removed.
Both ways are not really better than the current way.

My suggestion would be much faster since you just have to read 1 line in 1 file.

**Comment by VuiMuich** [comment]
I am fully aware, that having a look in each file is not as fast as just having the last successful exercise stored somewhere but I don't think an actual database might be needed, a simple `progress.toml` might be plenty sufficient.
Both was are actually better then compiling/testing each file, but of course having to look up a single value is the quickest way.

The big downside of just looking up the last successful exercise is, that this would completely miss out on updated or added exercises.

Possibly a `progress.toml` could be of this structure:
```toml
[[last_successful_exercise]]
name = "exercise5.rs"

[[marked_as_done]]
exercises = ["exercise1.rs", "exercise2.rs", "exercise4.rs"]

[[successfully_tested]]
exercises = ["exercise1.rs", "exercise2.rs", "exercise3.rs",  "exercise4.rs"]
```
Alternatively it could be:
```toml
[[Exercise]]
name = "exercise1.rs",
marked_as_done = true,
tested_successful = true

[[Exercise]]
name = "exercise2.rs",
marked_as_done = true,
tested_successful = true

[[Exercise]]
name = "exercise3.rs",
marked_as_done = false,
tested_successful = true

[[Exercise]]
name = "exercise4.rs",
marked_as_done = true,
tested_successful = true

[[Exercise]]
name = "exercise5.rs",
marked_as_done = false,
tested_successful = false

[[Exercise]]
name = "exercise6.rs",
marked_as_done = false,
tested_successful = false
```
Processing such toml files should take a neglegible amount of time and basically be the same UE as only reading a single line file
